name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: C Program Test
      id: c-program-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: C Program Test
        setup-command: ''
        command: gcc -o program program.c && ./program
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        C-PROGRAM-TEST_RESULTS: "${{steps.c-program-test.outputs.result}}"
      with:
        runners: c-program-test
